// 勋章获取情况
const TYPE_CONFIG_MEDAL_NULL = 0
const TYPE_CONFIG_MEDAL_GET = 1
const TYPE_CONFIG_MEDAL_WEAR = 3

module.exports = {
    TYPE_CONFIG_MEDAL_NULL,
    TYPE_CONFIG_MEDAL_GET,
    TYPE_CONFIG_MEDAL_WEAR
}
